### PR TITLE
adding https support for start command

### PR DESCRIPTION
**Pull request by garbas**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/neo/35)

### CODE REVIEW

**Comment by eliperelman** [comment]
Oooo haven't used reviewable in a while, let's see!

**Comment by eliperelman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[commands/start/index.js, line 12 \[r1\]](https://reviewable.io:443/reviews/mozilla/neo/35#-KOgdJ8yxBeLFpaun5hH:-KOgdJ8yxBeLFpaun5hI:bekkr45) ([raw file](https://github.com/mozilla/neo/blob/d7a9ba8f43c26a7044b9417e98e45a82ad45db72/commands/start/index.js#L12)):*
> ```JavaScript
>     devConfig;
> 
>   let schema = 'http';
> ```

```js
const schema = config.devServer.https ? 'https' : 'http';
const host = config.devServer.host || 'localhost';
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/neo/35)*

**Comment by garbas** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[commands/start/index.js, line 12 \[r1\]](https://reviewable.io:443/reviews/mozilla/neo/35#-KOgdJ8yxBeLFpaun5hH:-KOiIsExkMvHJYDj1vdi:b-xys6qd) ([raw file](https://github.com/mozilla/neo/blob/d7a9ba8f43c26a7044b9417e98e45a82ad45db72/commands/start/index.js#L12)):*
<details><summary><i>Previously, eliperelman (Eli Perelman) wrote…</i></summary>
> ```js
> const schema = config.devServer.https ? 'https' : 'http';
> const host = config.devServer.host || 'localhost';
> ```
</details>
eventually i get the formatting :) will fix it asap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/neo/35)*

**Comment by garbas** [comment]
damn ... i fixed you commend and then instead of pushing to my fork i pushed to origin. can you you can [this commit](https://github.com/mozilla/neo/commit/58ccd5b2876b363b05d9d154abdadd92f60765c1) if it is ok otherwise i'll revert it and we can continue review here.

i've also removed origin from my remotes so this will not happen again. i shouldn't push before coffee ... i learned my lesson :)

**Comment by eliperelman** [comment]
Haha no worries. And yes, looks good. (I eventually should walk through and put `const` on everything).

**Pull request closed without merging**
